##Anfang Stages of the pipeline / Globaler Bereich ------------------

stages:
  - lint
  - test
  - build
  - docker
  - secret-detection
##Ende Stages of the pipeline ------------------

variables:
  SECRET_DETECTION_ENABLED: 'true'

##Ende Globaler Bereich ------------------

##Anfang JOBS-Bereich ------------------
secret_detection:
  stage: secret-detection
include:
- template: Security/Secret-Detection.gitlab-ci.yml

##Ende JOBS-Bereich ------------------
